### ISSUE TITLE
ML Tags and About Us page

### ISSUE THREAD

**Issue by mattsul** [PHM-Data-Hub/app#27]
@PeterSulcs Here is our current draft for an about us page and possible ML tags. 
https://docs.google.com/document/d/1xDHux_nbDgqcQjf8k2JuIEe6eRF-CbhGvTpPSfKEEEk/edit?usp=sharing

**ML Tags**
We tried to think of the most general and inclusive ML tags for the datasets. The bolded tags are what would display on the website followed by possible algorithms a user might use. We tried to high all of the major ones. Please suggest any additions, edits, revisions, etc. incase we missed something! 

**About Us Page**
As I was reviewing it, it occurred to me that we may need a separate page to document the python package. 

Thanks for your help!

**Comment by PeterSulcs** [comment]
I think this issue can be closed as complete.
