### ISSUE TITLE
Netlify Failing to Deploy Blog 

### ISSUE THREAD

**Issue by mattsul** [PHM-Data-Hub/app#41]
**Netlify Failed Deployment**
Spent time searching for possible causes of the failed Netlify deployment. I cannot find anything within the code.

**Comment by PeterSulcs** [comment]
@mattsul Please create a branch and pull request that you think should publish the blogs so I can debug. Looks like previous PR was closed and I'm not sure if it's out of date now.

**Comment by mattsul** [comment]
Yeah! That was from a trial a did last week / two weeks ago where I moved the markdown files to the public folder / deleted it from blog content / routed things differently. I fixed all of that now. 

Everything should work locally now, however, the page still won't display on Netlify.
