### ISSUE TITLE
Brand existing tutorial as PHM Data Hub

### ISSUE THREAD

**Issue by PeterSulcs** [PHM-Data-Hub/app#5]
Change site to be PHM Data Hub and submit a Pull Request and look at resulting Netlify pipeline preview site

**Comment by cbarnes7** [comment]
Permission to PHM-Data-Hub/app.git denied to cbarnes7.
fatal: unable to access 'https://github.com/PHM-Data-Hub/app.git/': The requested URL returned error: 403

**Comment by cbarnes7** [comment]
I made an SSH key and added it to github.
Then followed these steps (https://gist.github.com/developius/c81f021eb5c5916013dc)
but got the following when i tried to push my branch:

```
git push origin cecilia
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Any idea? Sorry if it's obvious, never used an SSH key with git before

**Comment by PeterSulcs** [comment]
No problem. Please try doing a fresh clone in a different local directory. You will need to do:

`git clone git@github.com:PHM-Data-Hub/app.git`

**Comment by PeterSulcs** [comment]
@cbarnes7 please try again. I created a student team and gave write access to both repos. This should resolve the issue. Apologies for causing confusion with improper configuration. We are all learning. :)

**Comment by cbarnes7** [comment]
got mine to work using HTTPS! I think I must be using SSH wrong. Thanks for the quick responses
